import { AboutData } from "../models/about";

export const Mock_About: AboutData[] = [
  {
    id: 14,
    documentId: "ufhjpx0xulgbcjcqjv8nazh6",
    full_name: "Ayman Sedkey",
    createdAt: "2026-01-22T21:28:18.823Z",
    updatedAt: "2026-03-02T09:18:51.228Z",
    publishedAt: "2026-03-02T09:18:51.240Z",
    titles: [
      "Full Stack Developer",
      "MEARN Stack Specialist",
      "Front End Developer",
      "Back End Developer",
      "React & Angular Developer",
      "Node JS Developer",
    ],
    bio: [
      {
        type: "paragraph",
        children: [
          // { type: "text", text: "Hi! I'm " },
          // { type: "text", text: "Ayman Sedkey", bold: true },
          { type: "text", text: "A " },
          { type: "text", text: "Full-Stack Developer", bold: true },
          { type: "text", text: " who loves turning ideas into complete, " },
          { type: "text", text: "production-ready", bold: true },
          { type: "text", text: " web applications. I specialize in building " },
          { type: "text", text: "high-performance, SEO-friendly", bold: true },
          { type: "text", text: " web apps using the " },
          { type: "text", text: "MEARN stack", bold: true },
          { type: "text", text: "." },
        ],
      },
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "When I'm not coding, you'll find me exploring new web technologies, contributing to open-source, or working on ",
          },
          { type: "text", text: "freelance projects", bold: true },
          { type: "text", text: " for clients in " },
          { type: "text", text: "Egypt and Saudi Arabia", bold: true },
          { type: "text", text: "." },
        ],
      },
      {
        type: "paragraph",
        children: [
          { type: "text", text: "I thrive on " },
          { type: "text", text: "clean code, solid architecture", bold: true },
          { type: "text", text: ", and building solutions that make a " },
          { type: "text", text: "real impact", bold: true },
          { type: "text", text: "." },
        ],
      },
    ],
    frameworks: ["React", "Next", "Angular", "Node.js", "Mongo DB", "Express"],
    cv_url:
      "https://drive.google.com/file/d/1hUcU4v9jBDBWI61WmopTbcelmXlUgQLr/view?usp=sharing",
    sub_bio: [
      {
        type: "paragraph",
        children: [
          { type: "text", text: "Full Stack Developer (" },
          { type: "text", text: "MEARN", bold: true },
          { type: "text", text: ") with 1 year of experience. I build " },
          { type: "text", text: "fast, SEO-friendly, pixel-perfect", bold: true },
          {
            type: "text",
            text: " web apps from development to deployment. Certified by ",
          },
          {
            type: "text",
            text: "National Telecommunication Institute (NTI)",
            bold: true,
          },
          { type: "text", text: ". Experienced with " },
          { type: "text", text: "Saudi & Egyptian clients", bold: true },
          {
            type: "text",
            text: " in freelancing — dashboards, e-commerce, and landing pages. Let's turn your idea into a live website!",
          },
        ],
      },
    ],
    avilable_to_work: true,
    profile_photo: {
      id: 147,
      documentId: "cd4sxs6pkmq9fi6pfaopmu28",
      name: "me.png",
      alternativeText: null,
      caption: null,
      width: 816,
      height: 1224,
      formats: {
        thumbnail: {
          name: "thumbnail_me.png",
          hash: "thumbnail_me_4ff3fe73de",
          ext: ".png",
          mime: "image/png",
          path: null,
          width: 104,
          height: 156,
          size: 14.79,
          sizeInBytes: 14786,
          url: "https://res.cloudinary.com/dkxsrjol1/image/upload/v1772376769/thumbnail_me_4ff3fe73de.png",
          provider_metadata: {
            public_id: "thumbnail_me_4ff3fe73de",
            resource_type: "image",
          },
        },
        small: {
          name: "small_me.png",
          hash: "small_me_4ff3fe73de",
          ext: ".png",
          mime: "image/png",
          path: null,
          width: 333,
          height: 500,
          size: 101.55,
          sizeInBytes: 101547,
          url: "https://res.cloudinary.com/dkxsrjol1/image/upload/v1772376770/small_me_4ff3fe73de.png",
          provider_metadata: {
            public_id: "small_me_4ff3fe73de",
            resource_type: "image",
          },
        },
        medium: {
          name: "medium_me.png",
          hash: "medium_me_4ff3fe73de",
          ext: ".png",
          mime: "image/png",
          path: null,
          width: 500,
          height: 750,
          size: 213.58,
          sizeInBytes: 213575,
          url: "https://res.cloudinary.com/dkxsrjol1/image/upload/v1772376782/medium_me_4ff3fe73de.png",
          provider_metadata: {
            public_id: "medium_me_4ff3fe73de",
            resource_type: "image",
          },
        },
        large: {
          name: "large_me.png",
          hash: "large_me_4ff3fe73de",
          ext: ".png",
          mime: "image/png",
          path: null,
          width: 667,
          height: 1000,
          size: 361.4,
          sizeInBytes: 361399,
          url: "https://res.cloudinary.com/dkxsrjol1/image/upload/v1772376804/large_me_4ff3fe73de.png",
          provider_metadata: {
            public_id: "large_me_4ff3fe73de",
            resource_type: "image",
          },
        },
      },
      hash: "me_4ff3fe73de",
      ext: ".png",
      mime: "image/png",
      size: 137.47,
      url: "https://res.cloudinary.com/dkxsrjol1/image/upload/v1772376769/me_4ff3fe73de.png",
      previewUrl: null,
      provider: "cloudinary",
      provider_metadata: {
        public_id: "me_4ff3fe73de",
        resource_type: "image",
      },
      createdAt: "2026-03-01T14:53:24.997Z",
      updatedAt: "2026-03-01T14:53:24.997Z",
      publishedAt: "2026-03-01T14:53:24.998Z",
    },
  },
];
