import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "../components/NavigationBar";
import Footer from "../components/Footer";
import { ThemeProvider } from "../Providers/Theme-Provider";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Ayman Sedkey",
};
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});
// const Inte = Inter({
//   subsets: ["latin"]
// });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased px-5 lg:px-25 ${jakarta.className} bg-background text-foreground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange={true}
        >
          <NavigationBar />
          {children}
          {/* <ButtonsTop /> */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
