import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "../components/layout/NavigationBar";
import Footer from "../components/layout/Footer";
import { ThemeProvider } from "../Providers/Theme-Provider";
import { Plus_Jakarta_Sans } from "next/font/google";
import QueryProvider from "@/src/Providers/QueryProvider";
import CustomCursor from "../components/ui/CustomerCursor";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Ayman Sedkey",
};
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased px-5 lg:px-25 ${jakarta.className} bg-background text-foreground 
        selection:bg-primary/30 selection:text-primary/90
        transition-all duration-500
      `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange={true}
        >
          <QueryProvider>
            <CustomCursor />
            <NavigationBar />
            {children}
            {/* <ButtonsTop /> */}
            <Footer />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
