import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "../components/layout/NavigationBar";
import { ThemeProvider } from "../Providers/Theme-Provider";
import { Plus_Jakarta_Sans } from "next/font/google";
import QueryProvider from "@/src/Providers/QueryProvider";
// import { Analytics } from "@vercel/analytics/next"
import CustomCursor from "../components/ui/CustomerCursor";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Ayman Sedkey",
  openGraph: {
    images: ['/og-image.png'],
  },
};
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jakarta",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={`antialiased px-5 lg:px-25 ${jakarta.className} bg-background text-foreground 
        selection:bg-primary/30 selection:text-primary/90
      `}> */}
      <body className={`antialiased px-5 lg:px-25 ${jakarta.className} bg-background text-foreground 
        selection:bg-primary/30 selection:text-primary/90
      `}>
        {/* <Analytics /> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <CustomCursor />
            <NavigationBar />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
